# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('local', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Supporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('image_logo', models.URLField(verbose_name='Logo')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizers', to='events.Supporters', verbose_name='Organizers'),
        ),
        migrations.AddField(
            model_name='event',
            name='promoters',
            field=models.ManyToManyField(blank=True, related_name='promoters', to='events.Supporters', verbose_name='Promoters'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsors', to='events.Supporters', verbose_name='Sponsors'),
        ),
    ]
