# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='local',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='promoters',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supporters',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='events.Event', verbose_name='Supporters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supporters',
            name='types',
            field=models.CharField(choices=[('sponsors', 'Sponsors'), ('promoters', 'Promoters'), ('organizers', 'Organizers')], default=' ', max_length=155),
            preserve_default=False,
        ),
    ]
