# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171029_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporters',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='events.Event', verbose_name='Event'),
        ),
    ]
