# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171029_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
