# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='country',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
