# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporters',
            name='image_logo',
        ),
    ]
