# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20171117_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=150, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=150, verbose_name='State'),
        ),
    ]
