# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('photo', models.URLField(verbose_name='Photograph')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
