# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171029_2124'),
        ('talks', '0003_auto_20171029_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='description',
            new_name='speaker_description',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='title',
            new_name='talk_title',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='speaker',
        ),
        migrations.AddField(
            model_name='room',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='events.Event', verbose_name='Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='speaker_name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='speaker_photo',
            field=models.URLField(default=' ', verbose_name='Photograph'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
