# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_auto_20171031_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_title',
            field=models.CharField(max_length=255, verbose_name='Talk Title'),
        ),
    ]
