# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20171031_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='speaker_description',
            field=models.TextField(blank=True, verbose_name='Speaker Description'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_name',
            field=models.CharField(max_length=255, verbose_name='Speaker Name'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_photo',
            field=models.URLField(verbose_name='Speaker Photograph'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_description',
            field=models.TextField(blank=True, verbose_name='Talk Description'),
        ),
    ]
