# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171101_0015'),
        ('talks', '0007_auto_20171101_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.Event', verbose_name='Events'),
            preserve_default=False,
        ),
    ]
