# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_talk_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='events.Event', verbose_name='Events'),
        ),
    ]
