# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_auto_20171115_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_interval',
            field=models.BooleanField(default=False, verbose_name='Is Inverval'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Speaker Name'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_photo',
            field=models.URLField(blank=True, verbose_name='Speaker Photograph'),
        ),
    ]
