# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_auto_20171116_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='description_file',
            field=models.URLField(blank=True, verbose_name='Explanatory File'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='talks.Room', verbose_name='Room'),
        ),
    ]
